name: Deploy React Application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build --build-arg REACT_APP_BASE_URL='https://nationwide-motors-llc.com' --build-arg REACT_APP_FIREBASE_API_KEY='AIzaSyBQ-5IH0i_mWCL4SB8HHrYXuKQ2t_VO7P4' --build-arg REACT_APP_FIREBASE_AUTH_DOMAIN='movie-e7e4e.firebaseapp.com' --build-arg REACT_APP_FIREBASE_DATABASE_URL='https://movie-e7e4e-default-rtdb.asia-southeast1.firebasedatabase.app' --build-arg REACT_APP_FIREBASE_PROJECT_ID='movie-e7e4e' --build-arg REACT_APP_FIREBASE_STORAGE_BUCKET='movie-e7e4e.appspot.com' --build-arg REACT_APP_FIREBASE_MESSAGING_SENDER_ID='586418239627' --build-arg REACT_APP_FIREBASE_APP_ID='1:586418239627:web:7e47656aa5c5039d3ffc8e' --build-arg REACT_APP_FIREBASE_MEASUREMENT_ID='G-DL6W225Q17' --build-arg REACT_APP_ENV='production' -t harshkandera/nationwide-react:latest .

      - name: Publish Image to Docker Hub
        run: docker push harshkandera/nationwide-react:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from Docker Hub
        run: docker pull harshkandera/nationwide-react:latest

      - name: Delete old container
        run: docker rm -f reactjs-app-container || true

      - name: Run Docker Container
        run: docker run -d -p 3000:80 --name reactjs-app-container harshkandera/nationwide-react:latest

      - name: Clear Old Static Files
        run: sudo rm -rf /var/www/html/*

      - name: Copy Static Files from Docker Container
        run: docker cp reactjs-app-container:/usr/share/nginx/html/. /var/www/html/

      - name: Reload NGINX
        run: echo "Wh33l@Tr@ck99" | sudo -S systemctl reload nginx

